"use client";

import { useState } from "react";
import { ChevronDown, Sparkles } from "@gravity-ui/icons";
import { Reveal } from "./reveal";

const containerClass = "mx-auto w-full max-w-6xl px-4 sm:px-6 lg:px-8";

interface FAQItem {
  id: string;
  question: string;
  answer: string;
}

const FAQ_ITEMS: ReadonlyArray<FAQItem> = [
  {
    id: "accuracy",
    question: "How accurate are the AI nutrition estimates?",
    answer:
      "Nutritional values (calories, protein, carbs, fats) are estimates calculated by our AI engine. Actual values vary based on specific brand ingredients, portion sizes, and preparation methods. Always refer to official ingredient labels for precise dietary requirements.",
  },
  {
    id: "allergies",
    question: "How does FlavorAI handle food allergies and dietary restrictions?",
    answer:
      "You can configure dietary tags (Vegan, Keto, Gluten-Free, etc.) and explicit allergy exclusions in your profile or generator options. However, AI-generated recipes are for informational purposes only. Please double-check all ingredient labels for cross-contamination or allergen warnings before cooking.",
  },
  {
    id: "free",
    question: "Is FlavorAI completely free to use?",
    answer:
      "Yes! FlavorAI is 100% free to use. You can generate custom recipes, scan food nutrition from photos, chat with our kitchen assistant, and explore community recipes without any subscription fees.",
  },
  {
    id: "saving",
    question: "Can I save AI-generated recipes to my personal cookbook?",
    answer:
      "Absoutely. When you create an account, any recipe generated by AI can be saved as a private draft or published to the public community showcase for others to discover and rate.",
  },
  {
    id: "pantry-match",
    question: "How does the pantry matching algorithm work?",
    answer:
      "FlavorAI prioritizes the exact ingredients resting in your kitchen to minimize food waste. The AI calculates a match percentage based on used versus missing ingredients, ensuring recipes rely primarily on what you already own while suggesting optional missing items.",
  },
];

export function FaqAccordion() {
  const [openId, setOpenId] = useState<string | null>("accuracy");

  const toggleItem = (id: string) => {
    setOpenId((prev) => (prev === id ? null : id));
  };

  return (
    <section aria-labelledby="faq-heading" className={`${containerClass} py-16 sm:py-24 border-t border-border/80`}>
      <div className="mx-auto max-w-3xl text-center">
        <Reveal>
          <span className="inline-flex items-center gap-1.5 rounded-full border border-primary/20 bg-primary-soft px-3.5 py-1 text-xs font-bold text-primary-strong shadow-2xs">
            <Sparkles className="size-3.5 text-primary" aria-hidden="true" />
            Frequently Asked Questions
          </span>
        </Reveal>
        <Reveal delay={0.06}>
          <h2 id="faq-heading" className="mt-4 text-3xl font-extrabold tracking-tight text-heading sm:text-4xl">
            Everything you need to know
          </h2>
        </Reveal>
        <Reveal delay={0.12}>
          <p className="mt-3 text-base sm:text-lg leading-relaxed text-subtle-foreground">
            Clear, honest answers about AI recipe generation, nutrition estimates, and kitchen safety.
          </p>
        </Reveal>
      </div>

      <div className="mx-auto mt-12 max-w-3xl space-y-4">
        {FAQ_ITEMS.map((item, idx) => {
          const isOpen = openId === item.id;
          const answerId = `faq-answer-${item.id}`;

          return (
            <Reveal key={item.id} delay={idx * 0.06}>
              <div className="overflow-hidden rounded-2xl border border-border/80 bg-card shadow-2xs transition-colors hover:border-primary/30">
                <button
                  type="button"
                  onClick={() => toggleItem(item.id)}
                  aria-expanded={isOpen}
                  aria-controls={answerId}
                  className="flex w-full items-center justify-between gap-4 p-5 text-left text-sm font-bold text-heading sm:text-base focus-visible:outline focus-visible:outline-2 focus-visible:outline-primary"
                >
                  <span>{item.question}</span>
                  <span
                    className={`flex size-7 shrink-0 items-center justify-center rounded-full border border-border bg-background transition-transform duration-300 ${
                      isOpen ? "rotate-180 border-primary/30 bg-primary-soft text-primary-strong" : "text-muted-foreground"
                    }`}
                  >
                    <ChevronDown className="size-4" aria-hidden="true" />
                  </span>
                </button>

                {isOpen && (
                  <div id={answerId} className="border-t border-border/60 bg-background/50 p-5 text-xs sm:text-sm leading-relaxed text-subtle-foreground">
                    <p>{item.answer}</p>
                  </div>
                )}
              </div>
            </Reveal>
          );
        })}
      </div>
    </section>
  );
}
