import { fireEvent, render, screen } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";
import { RatingStars } from "../src/components/recipes/rating-stars";
import { RecipeCard } from "../src/components/recipes/recipe-card";
import { DisclaimerBanner } from "../src/components/ui/disclaimer-banner";
import { TagInput } from "../src/components/ui/tag-input";

describe("Frontend Unit & Component: Core UI Primitives", () => {
  describe("RatingStars component", () => {
    it("renders read-only rating with fractional score and review count", () => {
      render(
        <RatingStars
          value={4.7}
          count={12}
          size="md"
        />,
      );

      expect(screen.getByText("4.7")).toBeInTheDocument();
      expect(screen.getByText("(12)")).toBeInTheDocument();
    });

    it("renders interactive rating mode and calls onRate when a star is clicked", () => {
      const handleRate = vi.fn();
      render(
        <RatingStars
          value={3}
          interactive
          onRate={handleRate}
        />,
      );

      const fiveStarOption = screen.getByRole("radio", { name: "5 stars" });
      fireEvent.click(fiveStarOption);

      expect(handleRate).toHaveBeenCalledWith(5);
    });
  });

  describe("RecipeCard component", () => {
    it("renders title, category, difficulty, dietary badges, and time", () => {
      const mockRecipe = {
        id: "rec-123",
        title: "Creamy Tuscan Chicken",
        slug: "creamy-tuscan-chicken",
        summary: "Sun-dried tomatoes and spinach in a rich garlic cream sauce",
        imageUrl: "https://example.com/chicken.jpg",
        difficulty: "easy" as const,
        cuisine: "Italian",
        category: "main-course" as const,
        source: "ai" as const,
        status: "published" as const,
        dietaryLabels: ["gluten-free" as const, "high-protein" as const],
        totalTimeMinutes: 30,
        averageRating: 4.8,
        ratingCount: 15,
        favoriteCount: 7,
      };

      render(<RecipeCard recipe={mockRecipe} />);

      expect(screen.getByText("Creamy Tuscan Chicken")).toBeInTheDocument();
      expect(screen.getByText(/Sun-dried tomatoes and spinach/)).toBeInTheDocument();
      expect(screen.getByText("Main Course")).toBeInTheDocument();
      expect(screen.getByText("Easy")).toBeInTheDocument();
      expect(screen.getByText("Gluten Free")).toBeInTheDocument();
      expect(screen.getByText("High Protein")).toBeInTheDocument();
      expect(screen.getByText("30m")).toBeInTheDocument();
      expect(screen.getByText("AI Generated")).toBeInTheDocument();
    });
  });

  describe("TagInput component", () => {
    it("renders existing tags and triggers onChange when adding/removing tags", () => {
      const handleChange = vi.fn();
      render(
        <TagInput
          label="Allergies"
          value={["peanuts", "tree nuts"]}
          onChange={handleChange}
          placeholder="Add an allergy..."
        />,
      );

      expect(screen.getByText("peanuts")).toBeInTheDocument();
      expect(screen.getByText("tree nuts")).toBeInTheDocument();

      // Remove a chip
      const removePeanuts = screen.getByLabelText("Remove peanuts");
      fireEvent.click(removePeanuts);
      expect(handleChange).toHaveBeenCalledWith(["tree nuts"]);

      // Add a chip via typing + Enter
      const input = screen.getByPlaceholderText("Add an allergy...");
      fireEvent.change(input, { target: { value: "dairy" } });
      fireEvent.keyDown(input, { key: "Enter" });
      expect(handleChange).toHaveBeenCalledWith(["peanuts", "tree nuts", "dairy"]);
    });
  });

  describe("DisclaimerBanner component", () => {
    it("renders AI disclaimer with caution notice", () => {
      render(<DisclaimerBanner kind="ai" />);
      expect(screen.getByText("AI-generated content")).toBeInTheDocument();
      expect(
        screen.getByText(/This recipe was generated by AI/i),
      ).toBeInTheDocument();
    });

    it("renders Allergy disclaimer with warning notice", () => {
      render(<DisclaimerBanner kind="allergy" />);
      expect(screen.getByText("Allergy warning")).toBeInTheDocument();
      expect(
        screen.getByText(/AI cannot guarantee a recipe is free of allergens/i),
      ).toBeInTheDocument();
    });

    it("renders Nutrition disclaimer with informational notice", () => {
      render(<DisclaimerBanner kind="nutrition" />);
      expect(screen.getByText("Nutrition estimates")).toBeInTheDocument();
      expect(
        screen.getByText(/Nutrition values are approximations/i),
      ).toBeInTheDocument();
    });
  });
});
