import type { ReactNode } from "react";
import { Alert, type AlertVariant } from "./alert";

export type DisclaimerKind = "ai" | "nutrition" | "allergy";

const PRESETS: Record<DisclaimerKind, { variant: AlertVariant; title: string; body: string }> = {
  ai: {
    variant: "info",
    title: "AI-generated content",
    body: "This recipe was generated by AI and may contain mistakes. Review the ingredients and steps carefully before cooking.",
  },
  nutrition: {
    variant: "info",
    title: "Nutrition estimates",
    body: "Nutrition values are approximations based on ingredient data. They are provided for guidance only and are not medical advice.",
  },
  allergy: {
    variant: "warning",
    title: "Allergy warning",
    body: "AI cannot guarantee a recipe is free of allergens or compatible with your dietary restrictions. Always verify every ingredient independently if you have food allergies.",
  },
};

export function DisclaimerBanner({
  kind,
  children,
}: {
  kind: DisclaimerKind;
  children?: ReactNode;
}) {
  const preset = PRESETS[kind];
  return (
    <Alert variant={preset.variant} title={preset.title}>
      <p>{preset.body}</p>
      {children}
    </Alert>
  );
}
